# Header
menu:
  Home: /
  Arquivos: /posts
  Sobre: /about.html

# Logo Image Source
logo_src: /images/logo.png

# Theme Main Subtitle
subtitle_main: Tecnologia, informação, empreendedorismo e uma pitada de <a href='http://pastakitchen.net/wp-content/uploads/2015/11/PEPPER.jpg'>pimenta</a>.

# Theme Secondary subtitle
susbtitle_secondary: Luck Is What Happens When Preparation Meets Opportunity&#34; - Seneca.

# Footer About Section
about_footer: Todos os direitos reservados e guardados em uma caixa preta que ninguém sabe o paradeiro..

# Footer About Title
about_footer_title: Sobre

# Footer About Social Title
about_social_title: Siga

# Default post title
default_post_title: Sem Título

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: movendoideiascom
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
facebook_url: https://www.facebook.com/MovendoIdeias/
github_url: https://github.com/movendoideias
googleplus_url: https://plus.google.com/u/2/102233630350320179358/
email_url: mailto:contato@movendoideias.com

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false